# Generated by Django 6.1 on 2026-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backfill_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
