# Generated by Django 6.1 on 2026-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_totp_enabled_userprofile_totp_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recovery_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recovery_codes_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
