# Generated by Django 6.1 on 2026-08-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_alerts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
