# Generated by Django 6.1 on 2026-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_securitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
