# Generated by Django 6.1 on 2026-08-11 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ats_score', models.FloatField(default=0)),
                ('skill_score', models.FloatField(default=0)),
                ('keyword_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('education_score', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('matched_nice_to_have', models.JSONField(blank=True, default=list)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('concerns', models.JSONField(blank=True, default=list)),
                ('verdict', models.CharField(choices=[('strong_match', 'Strong Match'), ('good_match', 'Good Match'), ('possible_match', 'Possible Match'), ('weak_match', 'Weak Match')], default='possible_match', max_length=20)),
                ('stage', models.CharField(choices=[('rule_based', 'Rule-based'), ('ai_enhanced', 'AI-enhanced')], default='rule_based', max_length=20)),
                ('ai_analysis', models.TextField(blank=True, default='')),
                ('ai_verdict', models.CharField(blank=True, choices=[('strong_match', 'Strong Match'), ('good_match', 'Good Match'), ('possible_match', 'Possible Match'), ('weak_match', 'Weak Match')], default='', max_length=20)),
                ('ai_score_adjustment', models.IntegerField(default=0)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='candidates.application')),
            ],
            options={
                'ordering': ['-ats_score'],
            },
        ),
    ]
