# Generated by Django 6.1 on 2026-08-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresult',
            name='insight',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='recommendation',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
