# Generated by Django 6.1 on 2026-08-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_application_status_application_app_created_idx_and_more'),
        ('screening', '0002_screeningresult_insight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningresult',
            name='ats_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='screeningresult',
            index=models.Index(fields=['-created_at'], name='screen_created_idx'),
        ),
    ]
