# Generated by Django 6.1 on 2026-08-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='years_experience',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
