# Generated by Django 6.1 on 2026-08-11 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_applicationevent'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-created_at'], name='app_created_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['-created_at'], name='event_created_idx'),
        ),
    ]
