# Generated by Django 6.1 on 2026-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_application_status_application_app_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
